### ISSUE TITLE
Mouse annotation

### ISSUE THREAD

**Issue by imilenkovic** [ribosomeprofiling/riboflow#15]
Hello,

I would like to run the pipeline on some mouse Ribo-seq data, and I was wondering if you might have a mouse annotation file, such as this one for human: appris_human_24_01_2019_actual_regions.bed ?
Alternatively, could you point me to how I could generate such a file?

Thanks a lot!

Best,
Ivan

**Comment by hakanozadam** [comment]
Hello,

Yes we do have a mouse reference fore RiboFlow. They are in a separate repository:

https://github.com/ribosomeprofiling/references_for_riboflow

For mouse data, the reference files needed by RiboFlow are here:
https://github.com/ribosomeprofiling/references_for_riboflow/tree/master/transcriptome/mouse/v1/riboflow_annot_and_ref

If you want to generate your own reference, you can check out our scripts and python notebooks in the same repository:
https://github.com/ribosomeprofiling/references_for_riboflow/tree/master/transcriptome/mouse/v1/scripts

I hope this helps.
Best wishes.

**Comment by imilenkovic** [comment]
Hello,

Thank you very much for the quick answer!

I replaced all the human transcriptome/annotation files for mouse, and I ran the pipeline by encountered the following error:

[35/d57f83] NOTE: Missing output file(s) `KO.3.filter.bam` expected by process `filter (1)` -- Execution is retried (1)
[b8/43ea66] NOTE: Missing output file(s) `KO.2.filter.bam` expected by process `filter (2)` -- Execution is retried (1)
[4b/82e92a] NOTE: Missing output file(s) `WT.1.filter.bam` expected by process `filter (3)` -- Execution is retried (1)
[f9/4a8eb3] NOTE: Missing output file(s) `WT.2.filter.bam` expected by process `filter (4)` -- Execution is retried (1)
[54/48fbf5] NOTE: Missing output file(s) `WT.3.filter.bam` expected by process `filter (5)` -- Execution is retried (1)

In the project.yaml I instead of GSM1606107 and GSM1606108 I put WT and KO and gave paths to the 3 WT and 3 KO replicates (fastq files).

Do you maybe have an idea what went wrong?

Thank you!

**Comment by hakanozadam** [comment]
Did you also update the mouse reference entries in the project.yaml file?
If not, bowtie2 won't be able to find  reference files for the filtering.

More explicitly, the following entries need to be changed so that riboflow uses the mouse reference. You need to copy the mouse reference files from our github repo and provide their paths.

```
inpput:
  reference:
      filter: ./rf_sample_data/filter/human_rtRNA*

      transcriptome: ./rf_sample_data/transcriptome/appris_human_24_01_2019_selected*

      regions: ./rf_sample_data/annotation/appris_human_24_01_2019_actual_regions.bed

      transcript_lengths: ./rf_sample_data/annotation/appris_human_24_01_2019_selected.lengths.tsv
```
